version: '3'
services:
  srv-pg:
    image: ankane/pgvector:v0.5.0 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # 阿里云
    container_name: srv-pg
    hostname: ${PG_HOST}
    restart: always
    expose:
      - "${PG_PORT}"
    ports:
      - "${PG_PORT}:${PG_PORT}}"
    networks:
      - srv-net
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ./pg/data:/var/lib/postgresql/data

  srv-mysql:
    image: mysql:8.2
    container_name: srv-mysql
    hostname: ${MYSQL_HOST}
    privileged: true
    restart: always
    expose:
      - "3306"
    ports:
      - "${MYSQL_PORT_OUT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
      MYSQL_DATABASE: alron
      MYSQL_PASSWORD: ${MYSQL_PWD}
    command:
      --lower_case_table_names=1
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    networks:
      - srv-net

  srv-redis:
    image: redis:latest
    container_name: srv-redis
    hostname: ${REDIS_HOST}
    restart: always
    expose:
      - "6379"
    ports:
      - "${REDIS_PORT_OUT}:6379"
    logging:
      driver: 'json-file'
      options:
        max-size: '5g'
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf 
    command:
      redis-server /etc/redis/redis.conf
    networks:
      - srv-net

  srv-mongo:
    image: mongo:5.0.18
    container_name: srv-mongo
    hostname: ${MONGO_HOST}
    restart: always
    ports: # 生产环境建议不要暴露
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - srv-net
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    volumes:
      - ./mongo/data:/data/db

networks:
  srv-net:
    driver: bridge